export default {
  'quick-reference': 'Quick Reference',
  'getting-started': 'Getting Started',
  'daily-operations': 'Daily Operations',
  'multi-branch': 'Multi-Branch Accounting',
  'stock-accounting': 'Stock & Accounting Link',
  'vat-basics': 'VAT Basics',
  'business-types': 'Which Business Type Am I?',
  'sme-tot-basics': 'SME / TOT Basics',
  'importer-basics': 'Importer Basics',
  'rmg-exporter-basics': 'RMG Exporter Basics',
  'it-software-basics': 'IT / Software Basics',
  'service-vds-basics': 'Service Provider & VDS',
  'withholding-certificates': 'Withholding Certificates',
  invoicing: 'Invoicing',
  'auto-invoicing': 'Auto-Invoicing',
  'recurring-reminders': 'Recurring & Reminders',
  'credit-debit-notes': 'Credit & Debit Notes',
  'payment-verification': 'Payment Verification',
  'order-refunds': 'Order Refunds',
  'cod-settlement': 'COD Settlement',
  reports: 'Reports & Analysis',
  'settlement-model': 'How Settlement Works',
  permissions: 'Roles & Permissions',
}
